sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
before_install:
  - echo "//npme.eocng.org/:_authToken=$NPM_TOKEN" >> .npmrc
  - npm install -g npm@^3.0.0
install:
  - npm install
before_script:
  - npm prune
after_success:
  - npm run semantic-release && scripts/docker-build.sh
branches:
  except:
    # ignore git tags created by semantic-release, like "v1.2.3"
    - /^v\d+\.\d+\.\d+$/
